services:
  - type: worker
    name: telegram-reward-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        value: "20919872"
      - key: API_HASH
        value: "cf09a978564be23bb4325372820876b2"
      - key: SESSION_STRING
        value: "1BJWap1wBu3MLZX8B7fvntQMmQ_4fUMSvbQoeDHpQJv0mj747SLiUzC9r1QQnRW4T-vaV-7O50pFfZoC78Gk6oyVOMpVSuq4xf0sNsDB13VkRPIxoys5dQmnPDo9Dcd11DPlKhdL8cOOoZPzFys_e1vPr_dy0RphW9fjrFlop4IQRyd-X6y2OH8VEnPEqLmQ0Gl2XF5nTePmWdGEmqY-xKNZMekLWPWlM6DCq4Y_X_Sfq_4BrrNkoONFXXRHb96C7X7H_x0A-oq43712PeLCIuEvRpNPhWRq4tzRX3kU6VO2m9u1rS2Q4YkNaG6WVfVNs23gU7PiT67Eu_ycI-CVPtmNU1SsmFW0="
